name: "Create Release If Not Exist"
description: "Creates a GitHub release if it doesn't exist"
author: "topheman"
inputs:
  args:
    description: "Arguments you would pass to `gh release create` command that will run if the release doesn't exist"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run create-release-if-not-exist.sh
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/create-release-if-not-exist.sh ${{ inputs.args }}
      env:
        GH_TOKEN: ${{ github.token }}
branding:
  icon: "tag"
  color: "blue"
